### ISSUE TITLE
Error in running command documentation?

### ISSUE THREAD

**Issue by Fabelair** [Cereal84/AnadiCSV#11]
I can't run the program using " anadi " in my terminal...but "./anadi.sh"  works perfectly ....could change the documentation if it also works for everyone else?

**Comment by Cereal84** [comment]
The script anadi.sh should be copied in xxx/bin as anadi by "install.sh", of there Is a problem on the copy we need to resolve It.

**Comment by Fabelair** [comment]
Hey @Cereal84, I have created a pull request correcting this issue.

**Comment by Cereal84** [comment]
The problem is the copy in install.sh,.we don't need an alias
