### ISSUE TITLE
Run button not visible in the Query editor

### ISSUE THREAD

**Issue by 0xkafkaa** [Cereal84/AnadiCSV#13]
- As you can see the run button in the query editor is not visible by default. 
![Screenshot_2024-09-25_07-26-19](https://github.com/user-attachments/assets/32028141-b4aa-4f95-b50c-25af5cbdcd4a)
- After editing the editor height and adding a margin to the run button seems to work.
![Screenshot_2024-09-25_07-24-45](https://github.com/user-attachments/assets/ac137941-4839-4196-bb08-8e743310ab1b)

Let me know if this issue needs a PR.

**Comment by Cereal84** [comment]
Yes, can you work on it if you want.
I assign this issue to you :).

Thank you

**Comment by Cereal84** [comment]
Resolved in #15
