### ISSUE TITLE
Add support to Podman

### ISSUE THREAD

**Issue by Cereal84** [Cereal84/AnadiCSV#4]
The scripts supports only Docker image, we can extend this to Podman too.

**Comment by Fabelair** [comment]
Hey! can I work on that for u?

**Comment by Cereal84** [comment]
Hi @Fabelair, sure. I assign it to you.

**Comment by Fabelair** [comment]
Hey @Cereal84, I am doing everything I can, but I am incapable of running your program. I started on windows before understanding the install.sh was made for linux. after, I had to change the copy anadi.sh path because I don't have a .local folder...Still not able to run the anadi function in my command line. Do you think we could work on a way to make it work for windows and linux? And a way to make the downloading process easier for someone who would like to use your software?

edit: needed to create a lot of file to run the project...couldn't we create those files in the github and reference them there? (e.g. .config/anadi and local/bin/anadi)

**Comment by Fabelair** [comment]
@Cereal84 
After manually creating a anadi folder in /local/bin...If I run the anadi.sh program, it sais the .config/anadi/ file doesn't exist... I am not good enough to know exactly what you need to do, but I am pretty sure you are the only personne that can use your app right now.

**Comment by Cereal84** [comment]
Yes the project supports Ubuntu/Debian only at the moment.
Which Linux distro are you using ?

**Comment by Cereal84** [comment]
What do you mean with "And a way to make the downloading process easier for someone who would like to use your software?" ?

**Comment by Fabelair** [comment]
I think I just responded to you in my edit of my last comment

Ubuntu

**Comment by Cereal84** [comment]
On Ubuntu you should have *$HOME/.local/bin* directory, can you check if you have *$HOME/bin/* directory ?

Probably we can create the directory *$HOME/.config/anadi/* directly via *install.sh*, I opened a new issue about it #9 .

**Comment by Fabelair** [comment]
Hey @Cereal84, sorry I responded also in the other issue...but I only got the answer for the .config/anadi problem

**Comment by Cereal84** [comment]
@Fabelair Thanks to you I've created and fixed #9 .

**Comment by Cereal84** [comment]
> but

Can you check if you have $HOME/bin/ directory ?

**Comment by Fabelair** [comment]
no but everything works perfectly now...I think I miss understood the error (it probably only because the .config file was missing)

**Comment by Fabelair** [comment]
@Cereal84 in the anadi.sh file, it runs this command..."docker run -it -v "$CONF_PATH":/root/.config/anadi -v "$DATA_PATH":/data/ anadi:latest"... if I understood well, to use podman, the user would need to have it downloaded before hand (just like docker) and there would be a problem with the definition of anadi:latest ("podman run -it -v "$CONF_PATH":/root/.config/anadi -v "$DATA_PATH":/data/ anadi:latest"). Do you need the program to see if one of them is downloaded and use one of the two...or let the user decide? Not sure I understand everything...My current understanding of the use of docker rn is that docker is just your way to analyse the csv file.

**Comment by Cereal84** [comment]
Hi @Fabelair,
usually just one of them is installed in a machine so the script need to understand which one is installed and use it.
If both of them are installed we choose Docker.

**Comment by Cereal84** [comment]
@Fabelair I'm sorry but during my work on MacOS support I needed to use Podman and I've added both in #22
